//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.hr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкеты.
    /// </summary>
    // *** Start programmer edit section *** (Анкеты CustomAttributes)

    // *** End programmer edit section *** (Анкеты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетыE", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Должности as \'Должности\'",
            "Должности.Название as \'Название\'"}, Hidden=new string[] {
            "Должности.Название"})]
    [MasterViewDefineAttribute("АнкетыE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("АнкетыL", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Должности.Название as \'Название\'"})]
    public class Анкеты : IIS.hr.Физ_лица
    {
        
        private int fID;
        
        private string fЛК;
        
        private IIS.hr.Должности fДолжности;
        
        // *** Start programmer edit section *** (Анкеты CustomMembers)

        // *** End programmer edit section *** (Анкеты CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ID CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ID Get start)

                // *** End programmer edit section *** (Анкеты.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Анкеты.ID Get end)

                // *** End programmer edit section *** (Анкеты.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ID Set start)

                // *** End programmer edit section *** (Анкеты.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Анкеты.ID Set end)

                // *** End programmer edit section *** (Анкеты.ID Set end)
            }
        }
        
        /// <summary>
        /// ЛК.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ЛК CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ЛК CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ЛК
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Get start)

                // *** End programmer edit section *** (Анкеты.ЛК Get start)
                string result = this.fЛК;
                // *** Start programmer edit section *** (Анкеты.ЛК Get end)

                // *** End programmer edit section *** (Анкеты.ЛК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Set start)

                // *** End programmer edit section *** (Анкеты.ЛК Set start)
                this.fЛК = value;
                // *** Start programmer edit section *** (Анкеты.ЛК Set end)

                // *** End programmer edit section *** (Анкеты.ЛК Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Должности CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.hr.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Должности Get start)

                // *** End programmer edit section *** (Анкеты.Должности Get start)
                IIS.hr.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Анкеты.Должности Get end)

                // *** End programmer edit section *** (Анкеты.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Должности Set start)

                // *** End programmer edit section *** (Анкеты.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Анкеты.Должности Set end)

                // *** End programmer edit section *** (Анкеты.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыE", typeof(IIS.hr.Анкеты));
                }
            }
            
            /// <summary>
            /// "АнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыL", typeof(IIS.hr.Анкеты));
                }
            }
        }
    }
}
